"""Minimal HTML dashboard for portfolio, Greeks, and P&L.

Generates a static HTML file at ``runtime/dashboard.html`` that can be
opened in any browser.  Updated after each cycle by calling
``update_dashboard()``.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def update_dashboard(
    *,
    root_dir: Path,
    positions: list[dict[str, Any]],
    recent_exits: list[dict[str, Any]],
    recent_entries: list[dict[str, Any]],
    iv_history: dict[str, Any] | None = None,
    audit_summary: dict[str, Any] | None = None,
) -> Path:
    """Write ``runtime/dashboard.html`` and return its path."""

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pos_rows = _positions_table(positions)
    exit_rows = _exit_table(recent_exits)
    entry_rows = _entry_table(recent_entries)
    iv_rows = _iv_table(iv_history or {})
    stats = _stats(audit_summary or {})

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Trading Agent Dashboard</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         margin: 20px; background: #f5f5f5; color: #333; }}
  h1 {{ color: #1a1a2e; }}
  .stats {{ display: flex; gap: 16px; margin: 16px 0; flex-wrap: wrap; }}
  .stat {{ background: white; border-radius: 8px; padding: 16px 24px;
           box-shadow: 0 1px 3px rgba(0,0,0,0.1); min-width: 140px; }}
  .stat .label {{ font-size: 12px; color: #888; text-transform: uppercase; }}
  .stat .value {{ font-size: 24px; font-weight: bold; margin-top: 4px; }}
  .stat .value.green {{ color: #2ecc71; }}
  .stat .value.red {{ color: #e74c3c; }}
  table {{ width: 100%; border-collapse: collapse; background: white;
           border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);
           margin: 16px 0; }}
  th {{ background: #1a1a2e; color: white; padding: 10px 12px; text-align: left;
       font-size: 13px; }}
  td {{ padding: 8px 12px; border-bottom: 1px solid #eee; font-size: 13px; }}
  tr:hover td {{ background: #f9f9f9; }}
  .section {{ margin: 24px 0; }}
  .section h2 {{ font-size: 18px; color: #1a1a2e; border-bottom: 2px solid #1a1a2e;
                padding-bottom: 6px; }}
  .empty {{ color: #999; font-style: italic; padding: 16px; }}
  footer {{ margin-top: 32px; font-size: 11px; color: #aaa; }}
</style>
</head>
<body>
<h1>Trading Agent Dashboard</h1>
<p>Last updated: {now}</p>

{stats}

<div class="section">
<h2>Open Positions</h2>
{pos_rows}
</div>

<div class="section">
<h2>Recent Entries</h2>
{entry_rows}
</div>

<div class="section">
<h2>Recent Exits</h2>
{exit_rows}
</div>

<div class="section">
<h2>IV30 History</h2>
{iv_rows}
</div>

<footer>
  Auto-generated by trading_agent.dashboard &middot; Open in browser to view
</footer>
</body>
</html>"""

    out = root_dir / "runtime" / "dashboard.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    return out


def _positions_table(positions: list[dict]) -> str:
    if not positions:
        return '<p class="empty">No open positions</p>'
    headers = ["Code", "Ticker", "Side", "Entry", "Contracts", "P&L"]
    rows = ""
    for p in positions:
        pnl = p.get("unrealized_pnl", "n/a")
        pnl_cls = "green" if isinstance(pnl, (int, float)) and pnl >= 0 else "red"
        rows += f"""<tr>
  <td>{p.get('option_code','')}</td>
  <td>{p.get('ticker','')}</td>
  <td>{p.get('option_side','')}</td>
  <td>{p.get('entry_price','')}</td>
  <td>{p.get('contracts','')}</td>
  <td class="{pnl_cls}">{pnl}</td>
</tr>"""
    return f"<table><tr>{''.join(f'<th>{h}</th>' for h in headers)}</tr>{rows}</table>"


def _exit_table(exits: list[dict]) -> str:
    if not exits:
        return '<p class="empty">No recent exits</p>'
    headers = ["Code", "Ticker", "Reason", "P&L"]
    rows = ""
    for e in exits:
        pnl = e.get("pnl", "n/a")
        pnl_cls = "green" if isinstance(pnl, (int, float)) and pnl >= 0 else "red"
        rows += f"""<tr>
  <td>{e.get('option_code','')}</td>
  <td>{e.get('ticker','')}</td>
  <td>{e.get('reason','')}</td>
  <td class="{pnl_cls}">{pnl}</td>
</tr>"""
    return f"<table><tr>{''.join(f'<th>{h}</th>' for h in headers)}</tr>{rows}</table>"


def _entry_table(entries: list[dict]) -> str:
    if not entries:
        return '<p class="empty">No recent entries</p>'
    headers = ["Code", "Ticker"]
    rows = ""
    for e in entries:
        rows += f"""<tr>
  <td>{e.get('option_code','')}</td>
  <td>{e.get('ticker','')}</td>
</tr>"""
    return f"<table><tr>{''.join(f'<th>{h}</th>' for h in headers)}</tr>{rows}</table>"


def _iv_table(iv_data: dict) -> str:
    if not iv_data:
        return '<p class="empty">No IV30 data yet</p>'
    headers = ["Ticker", "Days", "Latest IV30"]
    rows = ""
    for ticker, entries in sorted(iv_data.items()):
        latest = entries[-1].get("iv30", "n/a") if entries else "n/a"
        rows += f"""<tr>
  <td>{ticker}</td>
  <td>{len(entries)}</td>
  <td>{latest}%</td>
</tr>"""
    return f"<table><tr>{''.join(f'<th>{h}</th>' for h in headers)}</tr>{rows}</table>"


def _stats(summary: dict) -> str:
    total_cycles = summary.get("cycle_completed", 0)
    entries = summary.get("order_placed", 0)
    rejected = summary.get("committee_run", 0) - summary.get("llm_usage", 0)
    return f"""<div class="stats">
  <div class="stat"><div class="label">Cycles</div><div class="value">{total_cycles}</div></div>
  <div class="stat"><div class="label">Entries</div><div class="value green">{entries}</div></div>
  <div class="stat"><div class="label">Committee Runs</div><div class="value">{summary.get('committee_run',0)}</div></div>
  <div class="stat"><div class="label">LLM Calls</div><div class="value">{summary.get('llm_usage',0)}</div></div>
</div>"""
